blog/urls.py
from django.urls import path
from blog.apps import BlogConfig
from blog.views import IndexListView, BlogCreateView, BlogUpdateView, BlogDeleteView, BlogDetailView, ContactsView, \
    BlogListView
from catalog.views import SignTemplateView

app_name = BlogConfig.name

urlpatterns = [
    path("", IndexListView.as_view(), name="index"),
    path('blog_list/', BlogListView.as_view(), name='blog_list'),
    path('blog/create/', BlogCreateView.as_view(), name='blog_create'),
    path("blog/<int:pk>/", BlogDetailView.as_view(), name="blog_detail"),
    path('blog/<int:pk>/update/', BlogUpdateView.as_view(), name='blog_update'),
    path('blog/<int:pk>/delete/', BlogDeleteView.as_view(), name='blog_delete'),
    path("blog/contacts/", ContactsView.as_view(), name="contacts"),
    path("blog/sign/", SignTemplateView.as_view(), name="sign"),


]

catalog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from catalog.apps import CatalogConfig
from catalog.views import ProductListView, ProductDetailView, ProductCreateView, IndexListView, \
    CategoryListView, SignTemplateView, ProductUpdateView, ProductDeleteView, ContactsView, CategoryProductListView

app_name = CatalogConfig.name

urlpatterns = [
    path("", IndexListView.as_view(), name="index"),
    path('catalog/product_list/', ProductListView.as_view(), name='product_list'),
    path('catalog/create/', ProductCreateView.as_view(), name='product_create'),
    path("catalog/<int:pk>/", cache_page(60)(ProductDetailView.as_view()), name="product_detail"),
    path('catalog/<int:pk>/update/', ProductUpdateView.as_view(), name='product_update'),
    path('catalog/<int:pk>/delete/', ProductDeleteView.as_view(), name='product_delete'),
    path("catalog/category/", CategoryListView.as_view(), name="category"),
    path('catalog/category/<int:pk>/products/', CategoryProductListView.as_view(), name='category_products'),
    path("catalog/contacts/", ContactsView.as_view(), name="contacts"),
    path("catalog/sign/", SignTemplateView.as_view(), name="sign"),

]

config/urls.py
from django.conf import settings
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import path, include
from catalog.views import permission_denied_view

handler403 = permission_denied_view

urlpatterns = [
                  path("admin/", admin.site.urls),
                  path('', include('catalog.urls', namespace='catalog')),
                  path('blog/', include('blog.urls', namespace='blog')),
                  path('users/', include('users.urls', namespace='users')),
                  path("tinymce/", include("tinymce.urls")),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from django.views.generic import TemplateView
from users.apps import UsersConfig
from users.views import RegisterView, CustomLogoutView, UserLoginView, email_verification

app_name = UsersConfig.name

urlpatterns = [
    path("register/", RegisterView.as_view(), name='register'),
    path("login/", UserLoginView.as_view(template_name='users/login.html'), name='login'),
    path("logout/", CustomLogoutView.as_view(next_page='users:logged_out'), name='logout'),
    path("logged_out/", TemplateView.as_view(template_name='users/logged_out.html'), name='logged_out'),
    path("email-confirm/<str:token>/", email_verification, name='email-confirm'),
]

blog/models.py
import os
from PIL import Image
from django.db import models


class Blog(models.Model):
    title = models.CharField(
        max_length=255,
        verbose_name="Заголовок"
    )
    content = models.TextField(
        verbose_name="Содержимое"
    )
    preview = models.ImageField(
        upload_to="blog/blog_previews",
        verbose_name="Превью изображения",
        blank=True,
        null=True
    )
    created_at = models.DateTimeField(
        auto_now_add=True,
        verbose_name="Дата создания"
    )
    is_published = models.BooleanField(
        default=False,
        verbose_name="Опубликовано"
    )
    updated_at = models.DateTimeField(
        auto_now=True,
        verbose_name="Дата последнего изменения",
    )
    views_count = models.PositiveIntegerField(
        default=0,
        verbose_name="Количество просмотров"
    )

    class Meta:
        verbose_name = "Моя статья"
        verbose_name_plural = "Мои статьи"
        ordering = ["-created_at"]

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)

        if self.preview:
            self.create_responsive_images()

    def create_responsive_images(self):
        img_path = self.preview.path
        filename, ext = os.path.splitext(os.path.basename(img_path))
        mobile_path = f"mobile/{filename}_300.webp"
        desktop_path = f"desktop/{filename}_900.webp"
        img = Image.open(img_path)
        img = img.convert("RGB")
        img_mobile = img.copy()
        img_mobile.thumbnail((300, 300))
        img_mobile.save(os.path.join(os.path.dirname(img_path), mobile_path), "WEBP", quality=85)
        img_desktop = img.copy()
        img_desktop.thumbnail((900, 900))
        img_desktop.save(os.path.join(os.path.dirname(img_path), desktop_path), "WEBP", quality=85)

        self.mobile_image = mobile_path
        self.desktop_image = desktop_path

        super().save()

blog/forms.py
from django import forms
from tinymce.widgets import TinyMCE
from .models import Blog

class BlogForm(forms.ModelForm):

    content = forms.CharField(widget=TinyMCE())

    class Meta:
        model = Blog
        fields = ('title', 'content', 'preview', )

blog/views.py
import os
from django.http import HttpResponse, JsonResponse
from django.shortcuts import render
from django.urls import reverse_lazy, reverse
from django.views import View
from django.views.generic import ListView, TemplateView, DeleteView, UpdateView, CreateView, DetailView
from blog.models import Blog
from django.conf import settings
from django.views.decorators.csrf import csrf_exempt
from .forms import BlogForm
from django.contrib.auth.mixins import LoginRequiredMixin


class IndexListView(TemplateView):
    model = Blog
    template_name = 'blog/index.html'


class BlogListView(ListView):
    model = Blog

    def get_queryset(self):
        return Blog.objects.filter(is_published=True).order_by('-created_at')


class BlogDetailView(DetailView):
    model = Blog

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        self.object.views_count += 1
        self.object.save()
        return self.object


class BlogCreateView(LoginRequiredMixin, CreateView):
    model = Blog
    form_class = BlogForm
    success_url = reverse_lazy('blog:blog_list')


class BlogUpdateView(LoginRequiredMixin, UpdateView):
    model = Blog
    form_class = BlogForm

    def get_success_url(self):
        return reverse('blog:blog_detail', args=[self.object.pk])


class BlogDeleteView(DeleteView):
    model = Blog
    success_url = reverse_lazy('blog:blog_list')


class ContactsView(View):
    template_name = "blog/contacts.html"

    def get(self, request):
        return render(request, self.template_name)

    def post(self, request):
        name = request.POST.get("name")
        message = request.POST.get("message")
        return HttpResponse(f"Спасибо, {name}! Ваше сообщение получено.")


@csrf_exempt
def tinymce_image_upload(request):
    if request.method == "POST":
        file = request.FILES.get("file")
        upload_dir = os.path.join(settings.MEDIA_ROOT, "tinymce_uploads")

        os.makedirs(upload_dir, exist_ok=True)

        file_path = os.path.join(upload_dir, file.name)

        with open(file_path, "wb+") as destination:
            for chunk in file.chunks():
                destination.write(chunk)

        file_url = f"{settings.MEDIA_URL}tinymce_uploads/{file.name}"

        return JsonResponse({"location": file_url})

    return JsonResponse({"error": "Invalid request"}, status=400)

blog/templates/blog/includes/footer.html
<footer class="footer fixed-bottom text-body-secondary py-3  text-bg-dark ">
    <div class="container ">
        <p class="float-end mb-1"><a href="#">Back to top</a></p>
        <p class="mb-1 text-white text-center">
            Copyright 2025 by Kazantsev A.A. All Rights Reserved. </p>
    </div>
</footer>

blog/templates/blog/includes/left_bar.html
{% load my_tags %}
<header data-bs-theme="dark">
<div class="d-flex flex-column flex-shrink-0 p-2 bg-body-tertiary h-100 position-fixed"
     style="width: 280px">
    <a href="{% url 'blog:index' %}"
       class="d-flex align-items-center mb-3 mb-md-0 me-md-auto link-body-emphasis text-decoration mx-auto">
        <svg xmlns="http://www.w3.org/2000/svg" width="36" height="36" fill="currentColor" class="bi bi-vector-pen"
             viewBox="0 0 16 16">
            <path fill-rule="evenodd"
                  d="M10.646.646a.5.5 0 0 1 .708 0l4 4a.5.5 0 0 1 0 .708l-1.902 1.902-.829 3.313a1.5 1.5 0 0 1-1.024 1.073L1.254 14.746 4.358 4.4A1.5 1.5 0 0 1 5.43 3.377l3.313-.828zm-1.8 2.908-3.173.793a.5.5 0 0 0-.358.342l-2.57 8.565 8.567-2.57a.5.5 0 0 0 .34-.357l.794-3.174-3.6-3.6z"/>
            <path fill-rule="evenodd" d="M2.832 13.228 8 9a1 1 0 1 0-1-1l-4.228 5.168-.026.086z"/>
        </svg>
        <span class="fs-2 md-4">Blog</span>
    </a>
    <hr/>
    <h4 class="text-center">Навигация</h4>
    <div class="col p-4 py-3">
        <ul class="list-unstyled md-5">
            <li><a href="{% url 'blog:index' %}" class="nav-link link-body-emphasis text-white">
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                     class="bi bi-house me-2" viewBox="0 0 16 16">
                    <path d="M8.707 1.5a1 1 0 0 0-1.414 0L.646 8.146a.5.5 0 0 0 .708.708L2 8.207V13.5A1.5 1.5 0 0 0 3.5 15h9a1.5 1.5 0 0 0 1.5-1.5V8.207l.646.647a.5.5 0 0 0 .708-.708L13 5.793V2.5a.5.5 0 0 0-.5-.5h-1a.5.5 0 0 0-.5.5v1.293zM13 7.207V13.5a.5.5 0 0 1-.5.5h-9a.5.5 0 0 1-.5-.5V7.207l5-5z"/>
                </svg>
                Главная </a></li>
            <li><a href="#" class="nav-link link-body-emphasis text-white">
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                     class="bi bi-newspaper me-2" viewBox="0 0 16 16">
                    <path d="M0 2.5A1.5 1.5 0 0 1 1.5 1h11A1.5 1.5 0 0 1 14 2.5v10.528c0 .3-.05.654-.238.972h.738a.5.5 0 0 0 .5-.5v-9a.5.5 0 0 1 1 0v9a1.5 1.5 0 0 1-1.5 1.5H1.497A1.497 1.497 0 0 1 0 13.5zM12 14c.37 0 .654-.211.853-.441.092-.106.147-.279.147-.531V2.5a.5.5 0 0 0-.5-.5h-11a.5.5 0 0 0-.5.5v11c0 .278.223.5.497.5z"/>
                    <path d="M2 3h10v2H2zm0 3h4v3H2zm0 4h4v1H2zm0 2h4v1H2zm5-6h2v1H7zm3 0h2v1h-2zM7 8h2v1H7zm3 0h2v1h-2zm-3 2h2v1H7zm3 0h2v1h-2zm-3 2h2v1H7zm3 0h2v1h-2z"/>
                </svg>
                Новости </a></li>
            <li><a href="{% url 'blog:blog_list' %}" class="nav-link link-body-emphasis text-white">
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                     class="bi bi-newspaper me-2"
                     viewBox="0 0 16 16">
                    <path d="m13.498.795.149-.149a1.207 1.207 0 1 1 1.707 1.708l-.149.148a1.5 1.5 0 0 1-.059 2.059L4.854 14.854a.5.5 0 0 1-.233.131l-4 1a.5.5 0 0 1-.606-.606l1-4a.5.5 0 0 1 .131-.232l9.642-9.642a.5.5 0 0 0-.642.056L6.854 4.854a.5.5 0 1 1-.708-.708L9.44.854A1.5 1.5 0 0 1 11.5.796a1.5 1.5 0 0 1 1.998-.001m-.644.766a.5.5 0 0 0-.707 0L1.95 11.756l-.764 3.057 3.057-.764L14.44 3.854a.5.5 0 0 0 0-.708z"/>
                </svg>
                Статьи </a></li>
            <li><a href="#" class="nav-link link-body-emphasis text-white">
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                     class="bi bi-stars me-2" viewBox="0 0 16 16">
                    <path d="M7.657 6.247c.11-.33.576-.33.686 0l.645 1.937a2.89 2.89 0 0 0 1.829 1.828l1.936.645c.33.11.33.576 0 .686l-1.937.645a2.89 2.89 0 0 0-1.828 1.829l-.645 1.936a.361.361 0 0 1-.686 0l-.645-1.937a2.89 2.89 0 0 0-1.828-1.828l-1.937-.645a.361.361 0 0 1 0-.686l1.937-.645a2.89 2.89 0 0 0 1.828-1.828zM3.794 1.148a.217.217 0 0 1 .412 0l.387 1.162c.173.518.579.924 1.097 1.097l1.162.387a.217.217 0 0 1 0 .412l-1.162.387A1.73 1.73 0 0 0 4.593 5.69l-.387 1.162a.217.217 0 0 1-.412 0L3.407 5.69A1.73 1.73 0 0 0 2.31 4.593l-1.162-.387a.217.217 0 0 1 0-.412l1.162-.387A1.73 1.73 0 0 0 3.407 2.31zM10.863.099a.145.145 0 0 1 .274 0l.258.774c.115.346.386.617.732.732l.774.258a.145.145 0 0 1 0 .274l-.774.258a1.16 1.16 0 0 0-.732.732l-.258.774a.145.145 0 0 1-.274 0l-.258-.774a1.16 1.16 0 0 0-.732-.732L9.1 2.137a.145.145 0 0 1 0-.274l.774-.258c.346-.115.617-.386.732-.732z"/>
                </svg>
                Категории </a></li>
        </ul>
    </div>
    <hr/>
    <div class="dropdown mx-4 ">
        <a href="#"
           class="d-flex align-items-center link-body-emphasis text-decoration-none dropdown-toggle"
           data-bs-toggle="dropdown"
           aria-expanded="false">
            {% if user.is_authenticated %}
            {% if user.avatar %}
            <img src="{{user.avatar|media_filter}}"
                 alt=""
                 width="42"
                 height="42"
                 class="rounded-circle me-2"/>
            {% else %}
            <img src="https://avatars.mds.yandex.net/i?id=ff9a158845fc70cc888f57b0f0daddae_l-5248605-images-thumbs&n=13"
                 alt=""
                 width="42"
                 height="42"
                 class="rounded-circle me-2"/>
            {% endif %}
            <strong>
                {% if user.username %}
                {{user.username}}
                {% else %}
                {{user.email}}
                {% endif %}
            </strong>
            {% else %}
            <img src="https://avatars.mds.yandex.net/i?id=ff9a158845fc70cc888f57b0f0daddae_l-5248605-images-thumbs&n=13"
                 alt=""
                 width="42"
                 height="42"
                 class="rounded-circle me-2"/>
            <strong>
                Гость
            </strong>
            {% endif %}
        </a>
        <ul class="dropdown-menu text-small shadow ">
            <li><a class="dropdown-item" href="{% url 'blog:blog_create' %}">Написать статью</a></li>
            <li><a class="dropdown-item" href="#">Настройки</a></li>
            <li><a class="dropdown-item" href="#">Профиль</a></li>
            <li>
                <hr class="dropdown-divider"/>
            </li>
            {% if user.is_authenticated %}
            <li>
                <form action="{% url 'users:logout' %}" method="post">
                    {% csrf_token %}
                    <button class="dropdown-item">Выйти</button>
                </form>
            </li>
            {% else %}
            <li><a class="dropdown-item" href="{% url 'users:login' %}">Войти</a></li>
            {% endif %}
        </ul>
    </div>
</div>
</header>

blog/templates/blog/includes/top_bar.html
<header data-bs-theme="dark">
    <div class="collapse text-bg-dark" id="navbarHeader">
        <div class="container">
            <div class="row">
                <div class="col-sm-8 col-md-7 py-4">
                    <h4>Навигация</h4>
                    <ul class="list-unstyled">
                        <li><a href="{% url 'blog:index' %}" class="text-white">Главная</a></li>
                        <li><a href="{% url 'blog:category' %}" class="text-white">Категории</a></li>
                        <li><a href="№" class="text-white">Новости</a></li>
                        <li><a href="{% url 'blog:blog_list' %}" class="text-white">Статьи</a></li>
                    </ul>
                </div>
                <div class="col-sm-4 offset-md-1 py-4 my-5">
                    {% if user.is_authenticated %}
                    <h4>Приветствуем,
                        {%if user.username%}
                        {{user.username}}
                        {% else %}
                        {{ user.email }}</h4>
                        {% endif %}
                    <ul class="list-unstyled">
                        <li>
                            <form action="{% url 'users:logout' %}" method="post">
                                {% csrf_token %}
                                <button class="btn btn-link text-white p-0">Выйти</button>
                            </form>
                        </li>
                    </ul>
                    {% else %}
                    <h4>Вход / Регистрация</h4>
                    <ul class="list-unstyled">
                        <li><a href="{% url 'users:login' %}" class="text-white">Войти</a></li>
                        <li><a href="{% url 'users:register' %}" class="text-white">Зарегистрироваться</a></li>
                    </ul>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
    <div class="navbar navbar-dark bg-dark shadow-sm">
        <div class="container">
            <a href="{% url 'catalog:index' %}" class="navbar-brand d-flex align-items-center">

                <strong class="glass-text fade-text">Blog</strong>
            </a>
            <button
                    class="navbar-toggler"
                    type="button"
                    data-bs-toggle="collapse"
                    data-bs-target="#navbarHeader"
                    aria-controls="navbarHeader"
                    aria-expanded="false"
                    aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
        </div>
    </div>
</header>