blog/urls.py
from django.urls import path
from blog.apps import BlogConfig
from blog.views import IndexListView, BlogCreateView, BlogUpdateView, BlogDeleteView, BlogDetailView, ContactsView, \
    BlogListView
from catalog.views import SignTemplateView

app_name = BlogConfig.name

urlpatterns = [
    path("", IndexListView.as_view(), name="index"),
    path('blog_list/', BlogListView.as_view(), name='blog_list'),
    path('blog/create/', BlogCreateView.as_view(), name='blog_create'),
    path("blog/<int:pk>/", BlogDetailView.as_view(), name="blog_detail"),
    path('blog/<int:pk>/update/', BlogUpdateView.as_view(), name='blog_update'),
    path('blog/<int:pk>/delete/', BlogDeleteView.as_view(), name='blog_delete'),
    path("blog/contacts/", ContactsView.as_view(), name="contacts"),
    path("blog/sign/", SignTemplateView.as_view(), name="sign"),


]

config/urls.py
from django.conf import settings
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import path, include
from catalog.views import permission_denied_view

handler403 = permission_denied_view

urlpatterns = [
                  path("admin/", admin.site.urls),
                  path('', include('catalog.urls', namespace='catalog')),
                  path('blog/', include('blog.urls', namespace='blog')),
                  path('users/', include('users.urls', namespace='users')),
                  path("tinymce/", include("tinymce.urls")),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
import os
from PIL import Image
from django.db import models


class Blog(models.Model):
    title = models.CharField(
        max_length=255,
        verbose_name="Заголовок"
    )
    content = models.TextField(
        verbose_name="Содержимое"
    )
    preview = models.ImageField(
        upload_to="blog/blog_previews",
        verbose_name="Превью изображения",
        blank=True,
        null=True
    )
    created_at = models.DateTimeField(
        auto_now_add=True,
        verbose_name="Дата создания"
    )
    is_published = models.BooleanField(
        default=False,
        verbose_name="Опубликовано"
    )
    updated_at = models.DateTimeField(
        auto_now=True,
        verbose_name="Дата последнего изменения",
    )
    views_count = models.PositiveIntegerField(
        default=0,
        verbose_name="Количество просмотров"
    )

    class Meta:
        verbose_name = "Моя статья"
        verbose_name_plural = "Мои статьи"
        ordering = ["-created_at"]

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)

        if self.preview:
            self.create_responsive_images()

    def create_responsive_images(self):
        img_path = self.preview.path
        filename, ext = os.path.splitext(os.path.basename(img_path))
        mobile_path = f"mobile/{filename}_300.webp"
        desktop_path = f"desktop/{filename}_900.webp"
        img = Image.open(img_path)
        img = img.convert("RGB")
        img_mobile = img.copy()
        img_mobile.thumbnail((300, 300))
        img_mobile.save(os.path.join(os.path.dirname(img_path), mobile_path), "WEBP", quality=85)
        img_desktop = img.copy()
        img_desktop.thumbnail((900, 900))
        img_desktop.save(os.path.join(os.path.dirname(img_path), desktop_path), "WEBP", quality=85)

        self.mobile_image = mobile_path
        self.desktop_image = desktop_path

        super().save()

blog/forms.py
from django import forms
from tinymce.widgets import TinyMCE
from .models import Blog

class BlogForm(forms.ModelForm):

    content = forms.CharField(widget=TinyMCE())

    class Meta:
        model = Blog
        fields = ('title', 'content', 'preview', )

blog/views.py
import os
from django.http import HttpResponse, JsonResponse
from django.shortcuts import render
from django.urls import reverse_lazy, reverse
from django.views import View
from django.views.generic import ListView, TemplateView, DeleteView, UpdateView, CreateView, DetailView
from blog.models import Blog
from django.conf import settings
from django.views.decorators.csrf import csrf_exempt
from .forms import BlogForm
from django.contrib.auth.mixins import LoginRequiredMixin


class IndexListView(TemplateView):
    model = Blog
    template_name = 'blog/index.html'


class BlogListView(ListView):
    model = Blog

    def get_queryset(self):
        return Blog.objects.filter(is_published=True).order_by('-created_at')


class BlogDetailView(DetailView):
    model = Blog

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        self.object.views_count += 1
        self.object.save()
        return self.object


class BlogCreateView(LoginRequiredMixin, CreateView):
    model = Blog
    form_class = BlogForm
    success_url = reverse_lazy('blog:blog_list')


class BlogUpdateView(LoginRequiredMixin, UpdateView):
    model = Blog
    form_class = BlogForm

    def get_success_url(self):
        return reverse('blog:blog_detail', args=[self.object.pk])


class BlogDeleteView(DeleteView):
    model = Blog
    success_url = reverse_lazy('blog:blog_list')


class ContactsView(View):
    template_name = "blog/contacts.html"

    def get(self, request):
        return render(request, self.template_name)

    def post(self, request):
        name = request.POST.get("name")
        message = request.POST.get("message")
        return HttpResponse(f"Спасибо, {name}! Ваше сообщение получено.")


@csrf_exempt
def tinymce_image_upload(request):
    if request.method == "POST":
        file = request.FILES.get("file")
        upload_dir = os.path.join(settings.MEDIA_ROOT, "tinymce_uploads")

        os.makedirs(upload_dir, exist_ok=True)

        file_path = os.path.join(upload_dir, file.name)

        with open(file_path, "wb+") as destination:
            for chunk in file.chunks():
                destination.write(chunk)

        file_url = f"{settings.MEDIA_URL}tinymce_uploads/{file.name}"

        return JsonResponse({"location": file_url})

    return JsonResponse({"error": "Invalid request"}, status=400)

blog/templates/blog/base.html
{% load static %}
{% load my_tags %}
<!DOCTYPE html>
<html lang="en" data-bs-theme="dark">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1"/>
    <meta name="description" content=""/>
    <meta name="generator" content="Astro v5.13.2"/>
    <title>
        {% if blog.title %}
        {{blog.title}}
        {% else %}
        Blog
        {% endif %}
    </title>
    <link rel="icon" type="image/x-icon" href="https://my.sky.pro/assets/skypro/favicon.ico">
    <link rel="stylesheet" href="{% static '/css/bootstrap.min.css' %}"/>
    <link rel="stylesheet" href="{% static '/css/style.css' %}"/>
    <script src="{% static 'js/color-modes.js' %}"></script>
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet"/>
    <style>
        .bd-placeholder-img {
          font-size: 1.125rem;
          text-anchor: middle;
          -webkit-user-select: none;
          -moz-user-select: none;
          user-select: none;
        }
        @media (min-width: 768px) {
          .bd-placeholder-img-lg {
            font-size: 3.5rem;
          }
        }
        .b-example-divider {
          width: 100%;
          height: 3rem;
          background-color: #0000001a;
          border: solid rgba(0, 0, 0, 0.15);
          border-width: 1px 0;
          box-shadow:
            inset 0 0.5em 1.5em #0000001a,
            inset 0 0.125em 0.5em #00000026;
        }
        .b-example-vr {
          flex-shrink: 0;
          width: 1.5rem;
          height: 100vh;
        }
        .bi {
          vertical-align: -0.125em;
          fill: currentColor;
        }
        .nav-scroller {
          position: relative;
          z-index: 2;
          height: 2.75rem;
          overflow-y: hidden;
        }
        .nav-scroller .nav {
          display: flex;
          flex-wrap: nowrap;
          padding-bottom: 1rem;
          margin-top: -1px;
          overflow-x: auto;
          text-align: center;
          white-space: nowrap;
          -webkit-overflow-scrolling: touch;
        }
        .btn-bd-primary {
          --bd-violet-bg: #712cf9;
          --bd-violet-rgb: 112.520718, 44.062154, 249.437846;
          --bs-btn-font-weight: 600;
          --bs-btn-color: var(--bs-white);
          --bs-btn-bg: var(--bd-violet-bg);
          --bs-btn-border-color: var(--bd-violet-bg);
          --bs-btn-hover-color: var(--bs-white);
          --bs-btn-hover-bg: #6528e0;
          --bs-btn-hover-border-color: #6528e0;
          --bs-btn-focus-shadow-rgb: var(--bd-violet-rgb);
          --bs-btn-active-color: var(--bs-btn-hover-color);
          --bs-btn-active-bg: #5a23c8;
          --bs-btn-active-border-color: #5a23c8;
        }
        .bd-mode-toggle {
          z-index: 1500;
        }
        .bd-mode-toggle .bi {
          width: 1em;
          height: 1em;
        }
        .bd-mode-toggle .dropdown-menu .active .bi {
          display: block !important;
        }
    </style>
</head>
<body class="d-flex flex-column min-vh-100">
<main class="flex-grow-1">

    {% if is_mobile %}
    {% include "blog/includes/top_bar.html" %}
    {% else %}
    {% include "blog/includes/left_bar.html" %}
    {% endif %}
    {% block content %}


    {% endblock %}
</main>
<script src="{% static 'js/bootstrap.bundle.js' %}" class="astro-vvvwv3sm"></script>
</body>
</html>

blog/templates/blog/blog_confirm_delete.html
{% extends 'blog/base.html' %}
{% block content %}
<div class="container bg-image  shadow p-3 bg-body-tertiary h-100 rounded">
    <div class="row">
        <h1 class="text-center">{{ object.name }}</h1>
        <div class="row ">
            <div class="col">
                <form class="row" method="post" enctype="multipart/form-data">
                    <div class="carf my-5">
                        <p class="card-text text-center fs-3">Вы действительно хотите удалить статью: <br> {{object.title}} ?</p>
                        <div class="card-body">
                            {% csrf_token %}
                            {{form.as_p}}
                        </div>
                    </div>
                    <div class="col text-center">
                        <button type="submit" class="btn btn-danger my-4">
                            Удалить
                        </button>
                        <a class="btn btn-dark" href="{% url 'blog:blog_list' %}">Отменить</a>
                    </div>

                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

blog/templates/blog/blog_detail.html
{% extends 'blog/base.html' %}
{% load my_tags %}
{% block content %}
<div class="container shadow bg-body-tertiary rounded">
<div class="container p-2">
    <h1 class="text-center p-3">{{ object.title }}</h1>
    <div class="row ">
        {% if object.preview %}
        <div class="card mb-3 mx-auto" style="max-width: 95%;">
            <div class="row g-0">
                <div class="col-md-12">
                    <div class="card-body">
                        <ul class="list-group list-group-flush">
                            <li class="list-group-item text-end"><p class="opacity-75 ">Название статьи: </p> <h3 class="text-center">{{ object.title }}</h3>
                            </li>
                        </ul>
                     <div><img class="row object-fit-cover mx-auto my-3" style="height: 400px; width: auto;"
                         src="{{ blog.preview|media_filter }}" alt="{{ blog.title }}">
                     </div>
                        <ul class="list-group list-group-flush">
                            <li class="list-group-item"><p class="opacity-75 text-end">Содержание: </p>{{ object.content | safe }}
                            </li>
                            <li class="list-group-item text-end"><p class="opacity-75">Дата создания:</p> {{ object.created_at|date:"d M Y" }}
                            </li>
                            <li class="list-group-item text-end"><p class="opacity-75">Дата последнего изменения:</p> {{ object.updated_at|date:"d M Y" }}
                            </li>
                            <li class="list-group-item text-end"><p class="opacity-75">Количество просмотров: </p>{{ object.views_count }}
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
            <a href="{% url 'blog:blog_list'%}" class="btn btn-dark">К списку статей</a>
        </div>
        {% endif %}
    </div>
</div>
</div>
{% endblock %}

blog/templates/blog/blog_form.html
{% extends 'blog/base.html' %}
{% block content %}
<div class="container bg-image shadow p-3 mb-5 bg-body-tertiary rounded">
    <h1 class="text-center fw-bold"> {% if object %}
                        Редактировать
                        {% else %}
                        Добавить
                        {% endif %}</h1>
    <div class="container my-5">
        <div class="row">
            <div class="col-2"></div>
            <div class="col-8">
                <form class="row" method="post" enctype="multipart/form-data">
                    <div class="card-body">
                        {% csrf_token %}
                        {{ form.media }}
                        {{ form.as_p }}
                    </div>
                    <div class="col-2"></div>
                    <button type="submit" class="btn btn-primary my-4">
                        {% if object %}
                        Сохранить
                        {% else %}
                        Создать
                        {% endif %}
                    </button>
                    <a class="btn btn-dark my-4" href="{% url 'blog:blog_list' %}">Отменить</a>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

blog/templates/blog/blog_list.html
{% extends 'blog/base.html' %}
{% load my_tags %}
{% block content %}
<div class="container bg-image  shadow p-3 bg-body-tertiary h-100 rounded">
    <div class="row">
        <div class="col-2"></div>
        <div class="col-8">

            <h1 class="text-center fw-bold mb-3"> Мои статьи </h1>

        </div>
        <div class="col-2">
            <a href="{% url 'blog:blog_create' %}" class="btn btn-dark text-end">Добавить статью</a>
        </div>
    </div>
    <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3 ">
        {% for blog in object_list %}
        <div class="col">
            <div class="card shadow-sm">
                {% if blog.preview %}
                <img class="object-fit-cover" style="height: 200px; width: 100%;"
                     src="{{ blog.preview|media_filter }}" alt="{{ blog.title }}">
                {% endif %}
                <div class="card-body">
                    <p class="card-text"> {{ blog.title |truncatechars:40}} </p>
                    <div
                            class="d-flex justify-content-between align-items-center">
                        <div class="btn-group">
                            <a class="btn btn-dark" href="{%url 'blog:blog_detail' blog.pk%}">Читать</a>
                            {% if user.is_authenticated %}
                            <a class="btn btn-dark" href="{%url 'blog:blog_update' blog.pk%}">Редактировать</a>
                            <a class="btn btn-dark" href="{%url 'blog:blog_delete' blog.pk%}">удалить</a>
                            {% endif %}
                        </div>
                        <small class="text-body-secondary">{{ blog.updated_at|date:"d M Y" }}</small>
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

blog/templates/blog/index.html
{% extends 'blog/base.html' %}
{% block content %}
<div class="container bg-image  shadow p-3 bg-body-tertiary h-100 rounded">
    <div class="row">
        <h1 class="text-center">Главная страница </h1>
    </div>
</div>

{% endblock %}

blog/templates/blog/sign.html
{% extends 'blog/base.html' %}
{% block content %}


{% endblock %}