blog/urls.py
from django.urls import path
from blog.apps import BlogConfig
from blog.views import IndexListView, BlogCreateView, BlogUpdateView, BlogDeleteView, BlogDetailView, ContactsView, \
    BlogListView
from catalog.views import SignTemplateView

app_name = BlogConfig.name

urlpatterns = [
    path("", IndexListView.as_view(), name="index"),
    path('blog_list/', BlogListView.as_view(), name='blog_list'),
    path('blog/create/', BlogCreateView.as_view(), name='blog_create'),
    path("blog/<int:pk>/", BlogDetailView.as_view(), name="blog_detail"),
    path('blog/<int:pk>/update/', BlogUpdateView.as_view(), name='blog_update'),
    path('blog/<int:pk>/delete/', BlogDeleteView.as_view(), name='blog_delete'),
    path("blog/contacts/", ContactsView.as_view(), name="contacts"),
    path("blog/sign/", SignTemplateView.as_view(), name="sign"),


]

catalog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from catalog.apps import CatalogConfig
from catalog.views import ProductListView, ProductDetailView, ProductCreateView, IndexListView, \
    CategoryListView, SignTemplateView, ProductUpdateView, ProductDeleteView, ContactsView, CategoryProductListView

app_name = CatalogConfig.name

urlpatterns = [
    path("", IndexListView.as_view(), name="index"),
    path('catalog/product_list/', ProductListView.as_view(), name='product_list'),
    path('catalog/create/', ProductCreateView.as_view(), name='product_create'),
    path("catalog/<int:pk>/", cache_page(60)(ProductDetailView.as_view()), name="product_detail"),
    path('catalog/<int:pk>/update/', ProductUpdateView.as_view(), name='product_update'),
    path('catalog/<int:pk>/delete/', ProductDeleteView.as_view(), name='product_delete'),
    path("catalog/category/", CategoryListView.as_view(), name="category"),
    path('catalog/category/<int:pk>/products/', CategoryProductListView.as_view(), name='category_products'),
    path("catalog/contacts/", ContactsView.as_view(), name="contacts"),
    path("catalog/sign/", SignTemplateView.as_view(), name="sign"),

]

config/urls.py
from django.conf import settings
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import path, include
from catalog.views import permission_denied_view

handler403 = permission_denied_view

urlpatterns = [
                  path("admin/", admin.site.urls),
                  path('', include('catalog.urls', namespace='catalog')),
                  path('blog/', include('blog.urls', namespace='blog')),
                  path('users/', include('users.urls', namespace='users')),
                  path("tinymce/", include("tinymce.urls")),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from django.views.generic import TemplateView
from users.apps import UsersConfig
from users.views import RegisterView, CustomLogoutView, UserLoginView, email_verification

app_name = UsersConfig.name

urlpatterns = [
    path("register/", RegisterView.as_view(), name='register'),
    path("login/", UserLoginView.as_view(template_name='users/login.html'), name='login'),
    path("logout/", CustomLogoutView.as_view(next_page='users:logged_out'), name='logout'),
    path("logged_out/", TemplateView.as_view(template_name='users/logged_out.html'), name='logged_out'),
    path("email-confirm/<str:token>/", email_verification, name='email-confirm'),
]

catalog/models.py
from django.db import models
from users.models import User
from django.db.models import ForeignKey


# Create your models here.


class Category(models.Model):
    name = models.CharField(
        max_length=150,
        unique=True,
        verbose_name="Наименование",
        help_text="Введите наименование продукта",
    )
    description = models.TextField(
        verbose_name="Описание",
        blank=True,
        null=True,
        help_text="Введите описание товара",
    )

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Категория"
        verbose_name_plural = "Категории"
        ordering = [
            "name",
        ]


class Product(models.Model):
    STATUS_CHOICES = (
        (False, 'Черновик'),
        (True, 'Опубликован'),
    )

    name = models.CharField(
        max_length=150,
        unique=True,
        verbose_name="Наименование",
    )
    description = models.TextField(
        blank=True,
        null=True,
        verbose_name="Описание",
    )
    image = models.ImageField(
        upload_to='catalog/images',
        blank=True, null=True,
        verbose_name="Изображение",
        help_text="Загрузите изображение",
    )
    category = models.ForeignKey(
        Category,
        on_delete=models.CASCADE,
        null=True,
        blank=True,
        verbose_name="Категория",
    )
    purchase_price = models.DecimalField(
        max_digits=10,
        decimal_places=2,
        verbose_name="Цена",
    )
    created_at = models.DateTimeField(
        auto_now_add=True,
        verbose_name="Дата создания",
    )
    updated_at = models.DateTimeField(
        auto_now=True,
        verbose_name="Дата последнего изменения",
    )
    views_counter = models.PositiveIntegerField(
        default=0,
        verbose_name='Счётчик просмотров',
        help_text='Укажите количество просмотров',
    )

    status = models.BooleanField(
        choices=STATUS_CHOICES,
        default=False,
        verbose_name='Статус публикации'
    )

    owner = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='products',
        verbose_name='Владелец'
    )

    def __str__(self):
        return self.name

    class Meta:
        permissions = [
            ('can_unpublish_product', 'Can unpublish product'),
        ]

catalog/forms.py
from django.forms import ModelForm
from django import forms
from catalog.models import Product
from django.core.exceptions import ValidationError

SPAM_WORDS = ['казино',
              'крипта',
              'биржа',
              'дешево',
              'бесплатно',
              'обман',
              'полиция',
              'радар',
              ]


class ProductForm(ModelForm):
    class Meta:
        model = Product
        fields = ['name', 'description', 'image', 'category', 'purchase_price',]
        #        fields = "__all__" # для вывода всех полей !!Заметка для себя
        exclude = ("views_counter", "owner")  # для фильтрации отмены вывода поля



    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs.update({'class': 'form-control'})

    def clean_name(self):
        name = self.cleaned_data.get('name')
        if name:
            for word in SPAM_WORDS:
                if word in name.lower():
                    raise forms.ValidationError(f"Название содержит запрещённое слово: {word}")
        return name

    def clean_description(self):
        description = self.cleaned_data.get('description')
        if description:
            for word in SPAM_WORDS:
                if word in description.lower():
                    raise forms.ValidationError(f"Описание содержит запрещённое слово: {word}")
        return description

    def clean_purchase_price(self):
        price = self.cleaned_data.get('purchase_price')
        if price < 0:
            raise forms.ValidationError("Цена не может быть отрицательной")
        return price

class ProductModeratorForm(ModelForm):
    class Meta:
        model = Product
        fields = ['status']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['status'].widget.attrs.update({'class': 'form-check-input'})

catalog/views.py
from django.core.cache import cache
from django.core.exceptions import PermissionDenied
from django.core.mail import send_mail
from django.shortcuts import redirect
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView, CreateView, UpdateView, TemplateView, DeleteView, View
from django.contrib import messages
from catalog.forms import ProductForm, ProductModeratorForm
from catalog.models import Category, Product
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from config.settings import EMAIL_HOST_USER


class IndexListView(ListView):
    model = Product
    template_name = 'catalog/index.html'


class CategoryListView(ListView):
    model = Category
    template_name = 'catalog/category.html'


CACHE_TTL = 60 * 5


class CategoryProductListView(ListView):
    model = Product
    template_name = 'catalog/category_products.html'
    context_object_name = 'object_list'
    paginate_by = 9

    def get_queryset(self):
        category_id = self.kwargs.get('pk')
        category = Category.objects.get(pk=category_id)
        user = self.request.user

        self.category = category
        cache_key = f'category_products_{category_id}_user_{user.pk if user.is_authenticated else "anon"}'
        products = cache.get(cache_key)
        if products is not None:
            return products

        qs = Product.objects.filter(category=category)
        if not user.is_authenticated:
            qs = qs.filter(status=True)
        elif not user.has_perm('catalog.can_unpublish_product'):
            qs = qs.filter(status=True) | qs.filter(owner=user)

        products = list(qs)
        cache.set(cache_key, products, CACHE_TTL)
        return products

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['category'] = getattr(self, 'category', None)
        return context


class ProductListView(ListView):
    model = Product

    def get_queryset(self):
        user = self.request.user

        if not user.is_authenticated:
            return Product.objects.filter(status=True)

        if user.has_perm('catalog.can_unpublish_product'):
            return Product.objects.all()

        return Product.objects.filter(status=True) | Product.objects.filter(owner=user)


class ProductDetailView(LoginRequiredMixin, DetailView):
    model = Product

    def get_object(self, queryset=None):
        obj = super().get_object(queryset)
        user = self.request.user

        if not obj.status:
            if not user.is_authenticated:
                raise PermissionDenied
            if obj.owner != user and not user.has_perm('catalog.can_unpublish_product'):
                raise PermissionDenied

        obj.views_counter += 1
        obj.save()
        return obj


class ProductCreateView(LoginRequiredMixin, PermissionRequiredMixin, CreateView):
    model = Product
    form_class = ProductForm
    success_url = reverse_lazy('catalog:product_list')
    permission_required = 'catalog.add_product'

    def form_valid(self, form):
        form.instance.owner = self.request.user
        return super().form_valid(form)


class ProductUpdateView(LoginRequiredMixin, UpdateView):
    model = Product
    success_url = reverse_lazy('catalog:product_list')

    def get_form_class(self):
        product = self.get_object()
        user = self.request.user

        if user == product.owner:
            return ProductForm
        elif user.has_perm('catalog.can_unpublish_product'):
            return ProductModeratorForm
        else:
            raise PermissionDenied


class ProductDeleteView(LoginRequiredMixin, DeleteView):
    model = Product
    success_url = reverse_lazy('catalog:product_list')

    def dispatch(self, request, *args, **kwargs):
        product = self.get_object()
        user = request.user

        if user == product.owner or user.has_perm('catalog.can_unpublish_product'):
            return super().dispatch(request, *args, **kwargs)
        raise PermissionDenied


class ContactsView(View):
    template_name = "catalog/contacts.html"

    def get(self, request):
        return render(request, self.template_name)

    def post(self, request):
        name = request.POST.get("name")
        phone = request.POST.get("phone")
        message_text = request.POST.get("message")

        if not name or not message_text:
            messages.error(request, "Имя и сообщение обязательны")
            return render(request, self.template_name, request.POST)

        subject = f"Сообщение от {name}"
        message = f"Имя: {name}\nТелефон: {phone}\nСообщение:\n{message_text}"
        from_email = EMAIL_HOST_USER
        recipient_list = [EMAIL_HOST_USER]

        try:
            send_mail(subject, message, from_email, recipient_list)
            messages.success(request, f"Спасибо, {name}! Ваше сообщение получено.")
        except Exception as e:
            messages.error(request, f"Ошибка при отправке: {e}")

        return redirect(request.path)


class SignTemplateView(TemplateView):
    template_name = "catalog/sign.html"


def permission_denied_view(request, exception=None):
    return render(request, "403.html", status=403)

catalog/templates/catalog/includes/button_theme.html
<svg xmlns="http://www.w3.org/2000/svg" class="d-none">
    <symbol id="check2" viewBox="0 0 16 16">
        <path
                d="M13.854 3.646a.5.5 0 0 1 0 .708l-7 7a.5.5 0 0 1-.708 0l-3.5-3.5a.5.5 0 1 1 .708-.708L6.5 10.293l6.646-6.647a.5.5 0 0 1 .708 0z"
        ></path>
    </symbol>
    <symbol id="circle-half" viewBox="0 0 16 16">
        <path
                d="M8 15A7 7 0 1 0 8 1v14zm0 1A8 8 0 1 1 8 0a8 8 0 0 1 0 16z"
        ></path>
    </symbol>
    <symbol id="moon-stars-fill" viewBox="0 0 16 16">
        <path
                d="M6 .278a.768.768 0 0 1 .08.858 7.208 7.208 0 0 0-.878 3.46c0 4.021 3.278 7.277 7.318 7.277.527 0 1.04-.055 1.533-.16a.787.787 0 0 1 .81.316.733.733 0 0 1-.031.893A8.349 8.349 0 0 1 8.344 16C3.734 16 0 12.286 0 7.71 0 4.266 2.114 1.312 5.124.06A.752.752 0 0 1 6 .278z"
        ></path>
        <path
                d="M10.794 3.148a.217.217 0 0 1 .412 0l.387 1.162c.173.518.579.924 1.097 1.097l1.162.387a.217.217 0 0 1 0 .412l-1.162.387a1.734 1.734 0 0 0-1.097 1.097l-.387 1.162a.217.217 0 0 1-.412 0l-.387-1.162A1.734 1.734 0 0 0 9.31 6.593l-1.162-.387a.217.217 0 0 1 0-.412l1.162-.387a1.734 1.734 0 0 0 1.097-1.097l.387-1.162zM13.863.099a.145.145 0 0 1 .274 0l.258.774c.115.346.386.617.732.732l.774.258a.145.145 0 0 1 0 .274l-.774.258a1.156 1.156 0 0 0-.732.732l-.258.774a.145.145 0 0 1-.274 0l-.258-.774a1.156 1.156 0 0 0-.732-.732l-.774-.258a.145.145 0 0 1 0-.274l.774-.258c.346-.115.617-.386.732-.732L13.863.1z"
        ></path>
    </symbol>
    <symbol id="sun-fill" viewBox="0 0 16 16">
        <path
                d="M8 12a4 4 0 1 0 0-8 4 4 0 0 0 0 8zM8 0a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-1 0v-2A.5.5 0 0 1 8 0zm0 13a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-1 0v-2A.5.5 0 0 1 8 13zm8-5a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1 0-1h2a.5.5 0 0 1 .5.5zM3 8a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1 0-1h2A.5.5 0 0 1 3 8zm10.657-5.657a.5.5 0 0 1 0 .707l-1.414 1.415a.5.5 0 1 1-.707-.708l1.414-1.414a.5.5 0 0 1 .707 0zm-9.193 9.193a.5.5 0 0 1 0 .707L3.05 13.657a.5.5 0 0 1-.707-.707l1.414-1.414a.5.5 0 0 1 .707 0zm9.193 2.121a.5.5 0 0 1-.707 0l-1.414-1.414a.5.5 0 0 1 .707-.707l1.414 1.414a.5.5 0 0 1 0 .707zM4.464 4.465a.5.5 0 0 1-.707 0L2.343 3.05a.5.5 0 1 1 .707-.707l1.414 1.414a.5.5 0 0 1 0 .708z"
        ></path>
    </symbol>
</svg>

<div
        class="dropdown position-fixed bottom-0 end-0 mb-3 me-3 bd-mode-toggle"
>
    <button
            class="btn btn-bd-primary py-2 dropdown-toggle d-flex align-items-center"
            id="bd-theme"
            type="button"
            aria-expanded="false"
            data-bs-toggle="dropdown"
            aria-label="Toggle theme (auto)"
    >
        <svg class="bi my-1 theme-icon-active" aria-hidden="true">
            <use href="#circle-half"></use>
        </svg>
        <span class="visually-hidden" id="bd-theme-text">Toggle theme</span>
    </button>
    <ul
            class="dropdown-menu dropdown-menu-end shadow"
            aria-labelledby="bd-theme-text"
    >
        <li>
            <button
                    type="button"
                    class="dropdown-item d-flex align-items-center"
                    data-bs-theme-value="light"
                    aria-pressed="false"
            >
                <svg class="bi me-2 opacity-50" aria-hidden="true">
                    <use href="#sun-fill"></use>
                </svg>
                Light
                <svg class="bi ms-auto d-none" aria-hidden="true">
                    <use href="#check2"></use>
                </svg>
            </button>
        </li>
        <li>
            <button
                    type="button"
                    class="dropdown-item d-flex align-items-center"
                    data-bs-theme-value="dark"
                    aria-pressed="false"
            >
                <svg class="bi me-2 opacity-50" aria-hidden="true">
                    <use href="#moon-stars-fill"></use>
                </svg>
                Dark
                <svg class="bi ms-auto d-none" aria-hidden="true">
                    <use href="#check2"></use>
                </svg>
            </button>
        </li>
        <li>
            <button
                    type="button"
                    class="dropdown-item d-flex align-items-center active"
                    data-bs-theme-value="auto"
                    aria-pressed="true"
            >
                <svg class="bi me-2 opacity-50" aria-hidden="true">
                    <use href="#circle-half"></use>
                </svg>
                Auto
                <svg class="bi ms-auto d-none" aria-hidden="true">
                    <use href="#check2"></use>
                </svg>
            </button>
        </li>
    </ul>
</div>
<svg xmlns="http://www.w3.org/2000/svg" class="d-none">
    <symbol id="bootstrap" viewBox="0 0 118 94">
        <title>Bootstrap</title>
        <path
                fill-rule="evenodd"
                clip-rule="evenodd"
                d="M24.509 0c-6.733 0-11.715 5.893-11.492 12.284.214 6.14-.064 14.092-2.066 20.577C8.943 39.365 5.547 43.485 0 44.014v5.972c5.547.529 8.943 4.649 10.951 11.153 2.002 6.485 2.28 14.437 2.066 20.577C12.794 88.106 17.776 94 24.51 94H93.5c6.733 0 11.714-5.893 11.491-12.284-.214-6.14.064-14.092 2.066-20.577 2.009-6.504 5.396-10.624 10.943-11.153v-5.972c-5.547-.529-8.934-4.649-10.943-11.153-2.002-6.484-2.28-14.437-2.066-20.577C105.214 5.894 100.233 0 93.5 0H24.508zM80 57.863C80 66.663 73.436 72 62.543 72H44a2 2 0 01-2-2V24a2 2 0 012-2h18.437c9.083 0 15.044 4.92 15.044 12.474 0 5.302-4.01 10.049-9.119 10.88v.277C75.317 46.394 80 51.21 80 57.863zM60.521 28.34H49.948v14.934h8.905c6.884 0 10.68-2.772 10.68-7.727 0-4.643-3.264-7.207-9.012-7.207zM49.948 49.2v16.458H60.91c7.167 0 10.964-2.876 10.964-8.281 0-5.406-3.903-8.178-11.425-8.178H49.948z"
        ></path>
    </symbol>
    <symbol id="home" viewBox="0 0 16 16">
        <path
                d="M8.354 1.146a.5.5 0 0 0-.708 0l-6 6A.5.5 0 0 0 1.5 7.5v7a.5.5 0 0 0 .5.5h4.5a.5.5 0 0 0 .5-.5v-4h2v4a.5.5 0 0 0 .5.5H14a.5.5 0 0 0 .5-.5v-7a.5.5 0 0 0-.146-.354L13 5.793V2.5a.5.5 0 0 0-.5-.5h-1a.5.5 0 0 0-.5.5v1.293L8.354 1.146zM2.5 14V7.707l5.5-5.5 5.5 5.5V14H10v-4a.5.5 0 0 0-.5-.5h-3a.5.5 0 0 0-.5.5v4H2.5z"
        ></path>
    </symbol>
    <symbol id="speedometer2" viewBox="0 0 16 16">
        <path
                d="M8 4a.5.5 0 0 1 .5.5V6a.5.5 0 0 1-1 0V4.5A.5.5 0 0 1 8 4zM3.732 5.732a.5.5 0 0 1 .707 0l.915.914a.5.5 0 1 1-.708.708l-.914-.915a.5.5 0 0 1 0-.707zM2 10a.5.5 0 0 1 .5-.5h1.586a.5.5 0 0 1 0 1H2.5A.5.5 0 0 1 2 10zm9.5 0a.5.5 0 0 1 .5-.5h1.5a.5.5 0 0 1 0 1H12a.5.5 0 0 1-.5-.5zm.754-4.246a.389.389 0 0 0-.527-.02L7.547 9.31a.91.91 0 1 0 1.302 1.258l3.434-4.297a.389.389 0 0 0-.029-.518z"
        ></path>
        <path
                fill-rule="evenodd"
                d="M0 10a8 8 0 1 1 15.547 2.661c-.442 1.253-1.845 1.602-2.932 1.25C11.309 13.488 9.475 13 8 13c-1.474 0-3.31.488-4.615.911-1.087.352-2.49.003-2.932-1.25A7.988 7.988 0 0 1 0 10zm8-7a7 7 0 0 0-6.603 9.329c.203.575.923.876 1.68.63C4.397 12.533 6.358 12 8 12s3.604.532 4.923.96c.757.245 1.477-.056 1.68-.631A7 7 0 0 0 8 3z"
        ></path>
    </symbol>
    <symbol id="table" viewBox="0 0 16 16">
        <path
                d="M0 2a2 2 0 0 1 2-2h12a2 2 0 0 1 2 2v12a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2V2zm15 2h-4v3h4V4zm0 4h-4v3h4V8zm0 4h-4v3h3a1 1 0 0 0 1-1v-2zm-5 3v-3H6v3h4zm-5 0v-3H1v2a1 1 0 0 0 1 1h3zm-4-4h4V8H1v3zm0-4h4V4H1v3zm5-3v3h4V4H6zm4 4H6v3h4V8z"
        ></path>
    </symbol>
    <symbol id="people-circle" viewBox="0 0 16 16">
        <path d="M11 6a3 3 0 1 1-6 0 3 3 0 0 1 6 0z"></path>
        <path
                fill-rule="evenodd"
                d="M0 8a8 8 0 1 1 16 0A8 8 0 0 1 0 8zm8-7a7 7 0 0 0-5.468 11.37C3.242 11.226 4.805 10 8 10s4.757 1.225 5.468 2.37A7 7 0 0 0 8 1z"
        ></path>
    </symbol>
    <symbol id="grid" viewBox="0 0 16 16">
        <path
                d="M1 2.5A1.5 1.5 0 0 1 2.5 1h3A1.5 1.5 0 0 1 7 2.5v3A1.5 1.5 0 0 1 5.5 7h-3A1.5 1.5 0 0 1 1 5.5v-3zM2.5 2a.5.5 0 0 0-.5.5v3a.5.5 0 0 0 .5.5h3a.5.5 0 0 0 .5-.5v-3a.5.5 0 0 0-.5-.5h-3zm6.5.5A1.5 1.5 0 0 1 10.5 1h3A1.5 1.5 0 0 1 15 2.5v3A1.5 1.5 0 0 1 13.5 7h-3A1.5 1.5 0 0 1 9 5.5v-3zm1.5-.5a.5.5 0 0 0-.5.5v3a.5.5 0 0 0 .5.5h3a.5.5 0 0 0 .5-.5v-3a.5.5 0 0 0-.5-.5h-3zM1 10.5A1.5 1.5 0 0 1 2.5 9h3A1.5 1.5 0 0 1 7 10.5v3A1.5 1.5 0 0 1 5.5 15h-3A1.5 1.5 0 0 1 1 13.5v-3zm1.5-.5a.5.5 0 0 0-.5.5v3a.5.5 0 0 0 .5.5h3a.5.5 0 0 0 .5-.5v-3a.5.5 0 0 0-.5-.5h-3zm6.5.5A1.5 1.5 0 0 1 10.5 9h3a1.5 1.5 0 0 1 1.5 1.5v3a1.5 1.5 0 0 1-1.5 1.5h-3A1.5 1.5 0 0 1 9 13.5v-3zm1.5-.5a.5.5 0 0 0-.5.5v3a.5.5 0 0 0 .5.5h3a.5.5 0 0 0 .5-.5v-3a.5.5 0 0 0-.5-.5h-3z"
        ></path>
    </symbol>
</svg>

catalog/templates/catalog/includes/content.html
<main>
    <section class="py-5 text-center container">
        <div class="row py-lg-5">
            <div class="col-lg-6 col-md-8 mx-auto">
                <h1 style="-webkit-text-stroke: 2px white; color: white;" class=" display-2 fw-light opacity-75 ">Rock
                    ballads</h1>
                <p class="lead text-body-secondary">
                    Магазин музыкальных инструментов
                </p>
            </div>
            <div class="container">
                {% if header_products %}
                {% for product in header_products %}
                <ul class="list-group opacity-95">
                    <li class="list-group-item text-start"><a href="{% url 'catalog:product_detail' product.pk %}">{{product.name|truncatechars:35}} </a>
                        <p> {{product.description|truncatechars:100}}</p></li>
                    {% empty %}
                    <li class="text-muted">Пока нет продуктов</li>
                </ul>
                {% endfor %}
                {% endif %}
            </div>
        </div>
    </section>
</main>

catalog/templates/catalog/includes/footer.html
<footer class="text-body-secondary py-3 mt-auto text-bg-dark">
    <div class="container ">
        <p class="float-end mb-1"><a href="#">Back to top</a></p>
        <p class="mb-1 text-white text-center">
Copyright 2025 by Kazantsev A.A. All Rights Reserved.
        </p>
    </div>
</footer>

catalog/templates/catalog/includes/inc_menu.html
<header data-bs-theme="dark">
    <div class="collapse text-bg-dark" id="navbarHeader">
        <div class="container">
            <div class="row">
                <div class="col-sm-8 col-md-7 py-4">
                    <h4>Навигация</h4>
                    <ul class="list-unstyled">
                        <li><a href="{% url 'catalog:index' %}" class="text-white">Главная</a></li>
                        <li><a href="{% url 'catalog:category' %}" class="text-white">Категории</a></li>
                        <li><a href="{% url 'catalog:product_list' %}" class="text-white">Продукты</a></li>
                        <li><a href="{% url 'catalog:contacts' %}" class="text-white">Контакты</a></li>
                        <li><a href="{% url 'blog:index' %}" class="text-white">Блог</a></li>
                    </ul>
                </div>
                <div class="col-sm-4 offset-md-1 py-4 my-5">
                    {% if user.is_authenticated %}
                    <h4>Приветствуем,
                        {%if user.username%}
                        {{user.username}}
                        {% else %}
                        {{ user.email }}</h4>
                        {% endif %}
                    <ul class="list-unstyled">
                        <li>
                            <form action="{% url 'users:logout' %}" method="post">
                                {% csrf_token %}
                                <button class="btn btn-link text-white p-0">Выйти</button>
                            </form>
                        </li>
                    </ul>
                    {% else %}
                    <h4>Вход / Регистрация</h4>
                    <ul class="list-unstyled">
                        <li><a href="{% url 'users:login' %}" class="text-white">Войти</a></li>
                        <li><a href="{% url 'users:register' %}" class="text-white">Зарегистрироваться</a></li>
                    </ul>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
    <div class="navbar navbar-dark bg-dark shadow-sm">
        <div class="container">
            <a href="{% url 'catalog:index' %}" class="navbar-brand d-flex align-items-center">

                <strong class="glass-text fade-text">Rock ballads</strong>
            </a>
            <button
                    class="navbar-toggler"
                    type="button"
                    data-bs-toggle="collapse"
                    data-bs-target="#navbarHeader"
                    aria-controls="navbarHeader"
                    aria-expanded="false"
                    aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
        </div>
    </div>
</header>