blog/urls.py
from django.urls import path
from blog.apps import BlogConfig
from blog.views import IndexListView, BlogCreateView, BlogUpdateView, BlogDeleteView, BlogDetailView, ContactsView, \
    BlogListView
from catalog.views import SignTemplateView

app_name = BlogConfig.name

urlpatterns = [
    path("", IndexListView.as_view(), name="index"),
    path('blog_list/', BlogListView.as_view(), name='blog_list'),
    path('blog/create/', BlogCreateView.as_view(), name='blog_create'),
    path("blog/<int:pk>/", BlogDetailView.as_view(), name="blog_detail"),
    path('blog/<int:pk>/update/', BlogUpdateView.as_view(), name='blog_update'),
    path('blog/<int:pk>/delete/', BlogDeleteView.as_view(), name='blog_delete'),
    path("blog/contacts/", ContactsView.as_view(), name="contacts"),
    path("blog/sign/", SignTemplateView.as_view(), name="sign"),


]

catalog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from catalog.apps import CatalogConfig
from catalog.views import ProductListView, ProductDetailView, ProductCreateView, IndexListView, \
    CategoryListView, SignTemplateView, ProductUpdateView, ProductDeleteView, ContactsView, CategoryProductListView

app_name = CatalogConfig.name

urlpatterns = [
    path("", IndexListView.as_view(), name="index"),
    path('catalog/product_list/', ProductListView.as_view(), name='product_list'),
    path('catalog/create/', ProductCreateView.as_view(), name='product_create'),
    path("catalog/<int:pk>/", cache_page(60)(ProductDetailView.as_view()), name="product_detail"),
    path('catalog/<int:pk>/update/', ProductUpdateView.as_view(), name='product_update'),
    path('catalog/<int:pk>/delete/', ProductDeleteView.as_view(), name='product_delete'),
    path("catalog/category/", CategoryListView.as_view(), name="category"),
    path('catalog/category/<int:pk>/products/', CategoryProductListView.as_view(), name='category_products'),
    path("catalog/contacts/", ContactsView.as_view(), name="contacts"),
    path("catalog/sign/", SignTemplateView.as_view(), name="sign"),

]

config/urls.py
from django.conf import settings
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import path, include
from catalog.views import permission_denied_view

handler403 = permission_denied_view

urlpatterns = [
                  path("admin/", admin.site.urls),
                  path('', include('catalog.urls', namespace='catalog')),
                  path('blog/', include('blog.urls', namespace='blog')),
                  path('users/', include('users.urls', namespace='users')),
                  path("tinymce/", include("tinymce.urls")),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

catalog/models.py
from django.db import models
from users.models import User
from django.db.models import ForeignKey


# Create your models here.


class Category(models.Model):
    name = models.CharField(
        max_length=150,
        unique=True,
        verbose_name="Наименование",
        help_text="Введите наименование продукта",
    )
    description = models.TextField(
        verbose_name="Описание",
        blank=True,
        null=True,
        help_text="Введите описание товара",
    )

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Категория"
        verbose_name_plural = "Категории"
        ordering = [
            "name",
        ]


class Product(models.Model):
    STATUS_CHOICES = (
        (False, 'Черновик'),
        (True, 'Опубликован'),
    )

    name = models.CharField(
        max_length=150,
        unique=True,
        verbose_name="Наименование",
    )
    description = models.TextField(
        blank=True,
        null=True,
        verbose_name="Описание",
    )
    image = models.ImageField(
        upload_to='catalog/images',
        blank=True, null=True,
        verbose_name="Изображение",
        help_text="Загрузите изображение",
    )
    category = models.ForeignKey(
        Category,
        on_delete=models.CASCADE,
        null=True,
        blank=True,
        verbose_name="Категория",
    )
    purchase_price = models.DecimalField(
        max_digits=10,
        decimal_places=2,
        verbose_name="Цена",
    )
    created_at = models.DateTimeField(
        auto_now_add=True,
        verbose_name="Дата создания",
    )
    updated_at = models.DateTimeField(
        auto_now=True,
        verbose_name="Дата последнего изменения",
    )
    views_counter = models.PositiveIntegerField(
        default=0,
        verbose_name='Счётчик просмотров',
        help_text='Укажите количество просмотров',
    )

    status = models.BooleanField(
        choices=STATUS_CHOICES,
        default=False,
        verbose_name='Статус публикации'
    )

    owner = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='products',
        verbose_name='Владелец'
    )

    def __str__(self):
        return self.name

    class Meta:
        permissions = [
            ('can_unpublish_product', 'Can unpublish product'),
        ]

catalog/forms.py
from django.forms import ModelForm
from django import forms
from catalog.models import Product
from django.core.exceptions import ValidationError

SPAM_WORDS = ['казино',
              'крипта',
              'биржа',
              'дешево',
              'бесплатно',
              'обман',
              'полиция',
              'радар',
              ]


class ProductForm(ModelForm):
    class Meta:
        model = Product
        fields = ['name', 'description', 'image', 'category', 'purchase_price',]
        #        fields = "__all__" # для вывода всех полей !!Заметка для себя
        exclude = ("views_counter", "owner")  # для фильтрации отмены вывода поля



    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs.update({'class': 'form-control'})

    def clean_name(self):
        name = self.cleaned_data.get('name')
        if name:
            for word in SPAM_WORDS:
                if word in name.lower():
                    raise forms.ValidationError(f"Название содержит запрещённое слово: {word}")
        return name

    def clean_description(self):
        description = self.cleaned_data.get('description')
        if description:
            for word in SPAM_WORDS:
                if word in description.lower():
                    raise forms.ValidationError(f"Описание содержит запрещённое слово: {word}")
        return description

    def clean_purchase_price(self):
        price = self.cleaned_data.get('purchase_price')
        if price < 0:
            raise forms.ValidationError("Цена не может быть отрицательной")
        return price

class ProductModeratorForm(ModelForm):
    class Meta:
        model = Product
        fields = ['status']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['status'].widget.attrs.update({'class': 'form-check-input'})

catalog/views.py
from django.core.cache import cache
from django.core.exceptions import PermissionDenied
from django.core.mail import send_mail
from django.shortcuts import redirect
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView, CreateView, UpdateView, TemplateView, DeleteView, View
from django.contrib import messages
from catalog.forms import ProductForm, ProductModeratorForm
from catalog.models import Category, Product
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from config.settings import EMAIL_HOST_USER


class IndexListView(ListView):
    model = Product
    template_name = 'catalog/index.html'


class CategoryListView(ListView):
    model = Category
    template_name = 'catalog/category.html'


CACHE_TTL = 60 * 5


class CategoryProductListView(ListView):
    model = Product
    template_name = 'catalog/category_products.html'
    context_object_name = 'object_list'
    paginate_by = 9

    def get_queryset(self):
        category_id = self.kwargs.get('pk')
        category = Category.objects.get(pk=category_id)
        user = self.request.user

        self.category = category
        cache_key = f'category_products_{category_id}_user_{user.pk if user.is_authenticated else "anon"}'
        products = cache.get(cache_key)
        if products is not None:
            return products

        qs = Product.objects.filter(category=category)
        if not user.is_authenticated:
            qs = qs.filter(status=True)
        elif not user.has_perm('catalog.can_unpublish_product'):
            qs = qs.filter(status=True) | qs.filter(owner=user)

        products = list(qs)
        cache.set(cache_key, products, CACHE_TTL)
        return products

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['category'] = getattr(self, 'category', None)
        return context


class ProductListView(ListView):
    model = Product

    def get_queryset(self):
        user = self.request.user

        if not user.is_authenticated:
            return Product.objects.filter(status=True)

        if user.has_perm('catalog.can_unpublish_product'):
            return Product.objects.all()

        return Product.objects.filter(status=True) | Product.objects.filter(owner=user)


class ProductDetailView(LoginRequiredMixin, DetailView):
    model = Product

    def get_object(self, queryset=None):
        obj = super().get_object(queryset)
        user = self.request.user

        if not obj.status:
            if not user.is_authenticated:
                raise PermissionDenied
            if obj.owner != user and not user.has_perm('catalog.can_unpublish_product'):
                raise PermissionDenied

        obj.views_counter += 1
        obj.save()
        return obj


class ProductCreateView(LoginRequiredMixin, PermissionRequiredMixin, CreateView):
    model = Product
    form_class = ProductForm
    success_url = reverse_lazy('catalog:product_list')
    permission_required = 'catalog.add_product'

    def form_valid(self, form):
        form.instance.owner = self.request.user
        return super().form_valid(form)


class ProductUpdateView(LoginRequiredMixin, UpdateView):
    model = Product
    success_url = reverse_lazy('catalog:product_list')

    def get_form_class(self):
        product = self.get_object()
        user = self.request.user

        if user == product.owner:
            return ProductForm
        elif user.has_perm('catalog.can_unpublish_product'):
            return ProductModeratorForm
        else:
            raise PermissionDenied


class ProductDeleteView(LoginRequiredMixin, DeleteView):
    model = Product
    success_url = reverse_lazy('catalog:product_list')

    def dispatch(self, request, *args, **kwargs):
        product = self.get_object()
        user = request.user

        if user == product.owner or user.has_perm('catalog.can_unpublish_product'):
            return super().dispatch(request, *args, **kwargs)
        raise PermissionDenied


class ContactsView(View):
    template_name = "catalog/contacts.html"

    def get(self, request):
        return render(request, self.template_name)

    def post(self, request):
        name = request.POST.get("name")
        phone = request.POST.get("phone")
        message_text = request.POST.get("message")

        if not name or not message_text:
            messages.error(request, "Имя и сообщение обязательны")
            return render(request, self.template_name, request.POST)

        subject = f"Сообщение от {name}"
        message = f"Имя: {name}\nТелефон: {phone}\nСообщение:\n{message_text}"
        from_email = EMAIL_HOST_USER
        recipient_list = [EMAIL_HOST_USER]

        try:
            send_mail(subject, message, from_email, recipient_list)
            messages.success(request, f"Спасибо, {name}! Ваше сообщение получено.")
        except Exception as e:
            messages.error(request, f"Ошибка при отправке: {e}")

        return redirect(request.path)


class SignTemplateView(TemplateView):
    template_name = "catalog/sign.html"


def permission_denied_view(request, exception=None):
    return render(request, "403.html", status=403)

catalog/templates/catalog/base.html
{% load static %}
<html lang="en" data-bs-theme="auto">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1"/>
    <meta name="description" content=""/>
    <meta
            name="author"
            content="Mark Otto, Jacob Thornton, and Bootstrap contributors"/>
    <meta name="generator" content="Astro v5.13.2"/>
    <title>
        {% block title %}
        {{ title }}
        {% endblock title %}
    </title>
    <link rel="icon" type="image/x-icon" href="https://my.sky.pro/assets/skypro/favicon.ico">
    <link rel="stylesheet" href="{% static '/css/bootstrap.min.css' %}"/>
    <link rel="stylesheet" href="{% static '/css/style.css' %}"/>
    <script src="{% static 'js/color-modes.js' %}"></script>
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet"/>
    <meta name="theme-color" content="#712cf9"/>
    <style>

        .bg-image {
        background-image: url('/media/catalog/images/logo.jpg');
        background-size: cover;
        background-attachment: fixed;
        background-repeat: no-repeat;
        background-position: center;
        }


        .bd-placeholder-img {
          font-size: 1.125rem;
          text-anchor: middle;
          -webkit-user-select: none;
          -moz-user-select: none;
          user-select: none;
        }
        @media (min-width: 768px) {
          .bd-placeholder-img-lg {
            font-size: 3.5rem;
          }
        }
        .b-example-divider {
          width: 100%;
          height: 3rem;
          background-color: #0000001a;
          border: solid rgba(0, 0, 0, 0.15);
          border-width: 1px 0;
          box-shadow:
            inset 0 0.5em 1.5em #0000001a,
            inset 0 0.125em 0.5em #00000026;
        }
        .b-example-vr {
          flex-shrink: 0;
          width: 1.5rem;
          height: 100vh;
        }
        .bi {
          vertical-align: -0.125em;
          fill: currentColor;
        }
        .nav-scroller {
          position: relative;
          z-index: 2;
          height: 2.75rem;
          overflow-y: hidden;
        }
        .nav-scroller .nav {
          display: flex;
          flex-wrap: nowrap;
          padding-bottom: 1rem;
          margin-top: -1px;
          overflow-x: auto;
          text-align: center;
          white-space: nowrap;
          -webkit-overflow-scrolling: touch;
        }
        .btn-bd-primary {
          --bd-violet-bg: #712cf9;
          --bd-violet-rgb: 112.520718, 44.062154, 249.437846;
          --bs-btn-font-weight: 600;
          --bs-btn-color: var(--bs-white);
          --bs-btn-bg: var(--bd-violet-bg);
          --bs-btn-border-color: var(--bd-violet-bg);
          --bs-btn-hover-color: var(--bs-white);
          --bs-btn-hover-bg: #6528e0;
          --bs-btn-hover-border-color: #6528e0;
          --bs-btn-focus-shadow-rgb: var(--bd-violet-rgb);
          --bs-btn-active-color: var(--bs-btn-hover-color);
          --bs-btn-active-bg: #5a23c8;
          --bs-btn-active-border-color: #5a23c8;
        }
        .bd-mode-toggle {
          z-index: 1500;
        }
        .bd-mode-toggle .bi {
          width: 1em;
          height: 1em;
        }
        .bd-mode-toggle .dropdown-menu .active .bi {
          display: block !important;
        }
    </style>
</head>
<body class="d-flex flex-column vh-100" data-bs-theme="dark">
<svg xmlns="http://www.w3.org/2000/svg" class="d-none">
    <symbol id="check2" viewBox="0 0 16 16">
        <path
                d="M13.854 3.646a.5.5 0 0 1 0 .708l-7 7a.5.5 0 0 1-.708 0l-3.5-3.5a.5.5 0 1 1 .708-.708L6.5 10.293l6.646-6.647a.5.5 0 0 1 .708 0z"
        ></path>
    </symbol>
    <symbol id="circle-half" viewBox="0 0 16 16">
        <path
                d="M8 15A7 7 0 1 0 8 1v14zm0 1A8 8 0 1 1 8 0a8 8 0 0 1 0 16z"
        ></path>
    </symbol>
    <symbol id="moon-stars-fill" viewBox="0 0 16 16">
        <path
                d="M6 .278a.768.768 0 0 1 .08.858 7.208 7.208 0 0 0-.878 3.46c0 4.021 3.278 7.277 7.318 7.277.527 0 1.04-.055 1.533-.16a.787.787 0 0 1 .81.316.733.733 0 0 1-.031.893A8.349 8.349 0 0 1 8.344 16C3.734 16 0 12.286 0 7.71 0 4.266 2.114 1.312 5.124.06A.752.752 0 0 1 6 .278z"
        ></path>
        <path
                d="M10.794 3.148a.217.217 0 0 1 .412 0l.387 1.162c.173.518.579.924 1.097 1.097l1.162.387a.217.217 0 0 1 0 .412l-1.162.387a1.734 1.734 0 0 0-1.097 1.097l-.387 1.162a.217.217 0 0 1-.412 0l-.387-1.162A1.734 1.734 0 0 0 9.31 6.593l-1.162-.387a.217.217 0 0 1 0-.412l1.162-.387a1.734 1.734 0 0 0 1.097-1.097l.387-1.162zM13.863.099a.145.145 0 0 1 .274 0l.258.774c.115.346.386.617.732.732l.774.258a.145.145 0 0 1 0 .274l-.774.258a1.156 1.156 0 0 0-.732.732l-.258.774a.145.145 0 0 1-.274 0l-.258-.774a1.156 1.156 0 0 0-.732-.732l-.774-.258a.145.145 0 0 1 0-.274l.774-.258c.346-.115.617-.386.732-.732L13.863.1z"
        ></path>
    </symbol>
    <symbol id="sun-fill" viewBox="0 0 16 16">
        <path
                d="M8 12a4 4 0 1 0 0-8 4 4 0 0 0 0 8zM8 0a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-1 0v-2A.5.5 0 0 1 8 0zm0 13a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-1 0v-2A.5.5 0 0 1 8 13zm8-5a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1 0-1h2a.5.5 0 0 1 .5.5zM3 8a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1 0-1h2A.5.5 0 0 1 3 8zm10.657-5.657a.5.5 0 0 1 0 .707l-1.414 1.415a.5.5 0 1 1-.707-.708l1.414-1.414a.5.5 0 0 1 .707 0zm-9.193 9.193a.5.5 0 0 1 0 .707L3.05 13.657a.5.5 0 0 1-.707-.707l1.414-1.414a.5.5 0 0 1 .707 0zm9.193 2.121a.5.5 0 0 1-.707 0l-1.414-1.414a.5.5 0 0 1 .707-.707l1.414 1.414a.5.5 0 0 1 0 .707zM4.464 4.465a.5.5 0 0 1-.707 0L2.343 3.05a.5.5 0 1 1 .707-.707l1.414 1.414a.5.5 0 0 1 0 .708z"
        ></path>
    </symbol>
</svg>
<div class="dropdown position-fixed bottom-0 end-0 mb-3 me-3 bd-mode-toggle">

    <ul
            class="dropdown-menu dropdown-menu-end shadow"
            aria-labelledby="bd-theme-text"
    >
        <li>
            <button
                    type="button"
                    class="dropdown-item d-flex align-items-center"
                    data-bs-theme-value="light"
                    aria-pressed="false"
            >
                <svg class="bi me-2 opacity-50" aria-hidden="true">
                    <use href="#sun-fill"></use>
                </svg>
                Light
                <svg class="bi ms-auto d-none" aria-hidden="true">
                    <use href="#check2"></use>
                </svg>
            </button>
        </li>
        <li>
            <button
                    type="button"
                    class="dropdown-item d-flex align-items-center"
                    data-bs-theme-value="dark"
                    aria-pressed="false"
            >
                <svg class="bi me-2 opacity-50" aria-hidden="true">
                    <use href="#moon-stars-fill"></use>
                </svg>
                Dark
                <svg class="bi ms-auto d-none" aria-hidden="true">
                    <use href="#check2"></use>
                </svg>
            </button>
        </li>
        <li>
            <button
                    type="button"
                    class="dropdown-item d-flex align-items-center active"
                    data-bs-theme-value="auto"
                    aria-pressed="true">
                <svg class="bi me-2 opacity-50" aria-hidden="true">
                    <use href="#circle-half"></use>
                </svg>
                Auto
                <svg class="bi ms-auto d-none" aria-hidden="true">
                    <use href="#check2"></use>
                </svg>
            </button>
        </li>
    </ul>
</div>
{% include 'catalog/includes/inc_menu.html' %}


{% block content %}

<div class="row my-2"></div>

{% endblock %}

{% include 'catalog/includes/footer.html' %}

<script src="{% static 'js/bootstrap.bundle.js' %}" class="astro-vvvwv3sm"></script>
</body>
</html>

catalog/templates/catalog/category.html
{% extends 'catalog/base.html' %}
{% load my_tags %}
{% block content %}
<div class="container bg-image my-5 shadow p-3 mb-5 bg-body-tertiary rounded">
    <h1 class="text-center fw-bold card box-shadow"> Категории товаров </h1>
    <div class="row ">
        <div class="container text-white">
            <ul>
                {% for objects in object_list %}
                <li>
                    <a href="{% url 'catalog:category_products' objects.pk %}">{{ objects.name }}</a>
                    — {{ objects.description | truncatechars:100 }}
                </li>
                {% endfor %}
            </ul>
        </div>
    </div>
</div>
{% endblock %}

catalog/templates/catalog/category_products.html
{% extends 'catalog/base.html' %}
{% block title %}{{ category.name }}{% endblock %}
{% load my_tags %}
{% block content %}

<div class="container bg-image my-5 shadow p-3 mb-5 bg-body-tertiary rounded">
    <div class="row mb-4">
        <div class="col-2"></div>
        <div class="col-8">
            <h1 class="text-center fw-bold card box-shadow">
                Товары категории: {{ category.name }}
            </h1>
        </div>
        <div class="col-2 text-end">
            {% if user.is_authenticated %}
                <a href="{% url 'catalog:product_create' %}" class="btn btn-dark">Добавить товар</a>
            {% endif %}
        </div>
    </div>
    <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
        {% for product in object_list %}
        <div class="col">
            <div class="card shadow-sm h-100">
                {% if product.image %}
                <img class="object-fit-cover" style="height: 200px; width: 100%;"
                     src="{{ product.image|media_filter }}" alt="{{ product.name }}">
                {% endif %}
                <div class="card-body d-flex flex-column">
                    <p class="card-text fw-bold">{{ product.name|truncatechars:40 }}</p>
                    <p class="card-text text-truncate">{{ product.description|truncatechars:100 }}</p>
                    <div class="mt-auto d-flex justify-content-between align-items-center">
                        <div class="btn-group">
                            <a class="btn btn-dark" href="{% url 'catalog:product_detail' product.pk %}">Перейти</a>
                            {% if user.is_authenticated %}
                                {% if product.owner == user or perms.catalog.can_unpublish_product %}
                                    <a class="btn btn-dark" href="{% url 'catalog:product_update' product.pk %}">Редактировать</a>
                                    <a class="btn btn-dark" href="{% url 'catalog:product_delete' product.pk %}">Удалить</a>
                                {% endif %}
                            {% endif %}
                        </div>
                        <small class="text-body-secondary">{{ product.updated_at|date:"d M Y" }}</small>
                    </div>
                </div>
            </div>
        </div>
        {% empty %}
            <p class="text-center mt-3">В этой категории нет товаров</p>
        {% endfor %}
    </div>
</div>

{% endblock %}

catalog/templates/catalog/index.html
{% extends 'catalog/base.html' %}
{% block title %}Главная страница каталога{% endblock %}

{% load my_tags %}
{% block content %}
<div class="container bg-image my-5 shadow p-3 mb-5 bg-body-tertiary rounded">
    <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3 ">
        {% include 'catalog/includes/content.html' %}
    </div>
</div>
{% endblock %}

catalog/templates/catalog/product_confirm_delete.html
{% extends 'catalog/base.html' %}
{% block title %}Удалить товар - {{ object.name }}{% endblock %}
{% block content %}
<div class="container bg-image my-5 shadow p-3 mb-5 bg-body-tertiary rounded">
    <h1 class="text-center">{{ object.name }}</h1>
    <div class="row ">
        <div class="col">
            <form class="row" method="post" enctype="multipart/form-data">
                <div class="carf">
                    <p class="card-text text-center fs-3">Действительно хотите удалить {{object.name}} ?</p>
                    <div class="card-body">
                        {% csrf_token %}
                        {{form.as_p}}
                    </div>
                </div>
                <div class="col text-center">
                    <button type="submit" class="btn btn-danger my-4">
                        Удалить
                    </button>
                    <a class="btn btn-dark" href="{% url 'catalog:product_list' %}">Отменить</a>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

catalog/templates/catalog/product_detail.html
{% extends 'catalog/base.html' %}
{% block title %}Детали товара{% endblock %}

{% load my_tags %}
{% block content %}
<div class="container bg-image my-5 shadow p-3 mb-5 bg-body-tertiary rounded">
    <h1 class="text-center card box-shadow">{{ object.name }}</h1>
    <div class="row ">
        {% if object.image %}
        <div class="card mb-3" style="max-width: 100%;">
            <div class="row g-0">
                <div class="col-md-4">
                    <img class="object-fit-cover" style="height: 100%; width: 100%;"
                         src="{{ object.image|media_filter }}" alt="{{ product.name }}">
                </div>
                <div class="col-md-8">
                    <div class="card-body">
                        <ul class="list-group list-group-flush">
                            <li class="list-group-item text-end"><p class="opacity-75 ">Название модели: </p> {{ object.name }}</li>
                            <li class="list-group-item"><p class="opacity-75 text-end">Описание: </p>{{ object.description }}</li>
                            <li class="list-group-item text-end"><p class="opacity-75">Категория товара:</p>
                                <a href="{% url 'catalog:category_products' object.category.pk %}">{{ object.category.name }}</a>
                            </li>
                            <li class="list-group-item text-end"><p class="opacity-75">Цена:</p> {{ object.purchase_price }}  руб.</li>
                            <li class="list-group-item text-end"><p class="opacity-75">Опубликовал: </p>{{ object.owner }}</li>
                            <li class="list-group-item text-end"><p class="opacity-75">Дата публикации: </p>{{ object.created_at|date:"d M Y" }}</li>
                            <li class="list-group-item text-end"><p class="opacity-75">Дата последнего изменения публикации: </p>{{ object.updated_at|date:"d M Y" }}</li>
                        </ul>
                    </div>
                </div>
            </div>
            <a href="{% url 'catalog:product_list'%}" class="btn btn-dark">К списку товаров</a>
        </div>
        {% endif %}
    </div>
</div>
{% endblock %}

catalog/templates/catalog/product_list.html
{% extends 'catalog/base.html' %}
{% block title %}Список товаров{% endblock %}
{% load my_tags %}
{% block content %}

<div class="container bg-image my-5 shadow p-3 mb-5 bg-body-tertiary rounded">
    <div class="row">
        <div class="col-2"></div>
        <div class="col-8">
            <h1 class="text-center fw-bold card box-shadow"> Наши товары </h1>
        </div>
        <div class="col-2">
            <a href="{% url 'catalog:product_create' %}" class="btn btn-dark text-end">Добавить товар</a>
        </div>
    </div>
    <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3 ">
        {% for product in object_list %}
        <div class="col">
            <div class="card shadow-sm">
                {% if product.image %}
                <img class="object-fit-cover" style="height: 200px; width: 100%;"
                     src="{{ product.image|media_filter }}" alt="{{ product.name }}">
                {% endif %}
                <div class="card-body">
                    <p class="card-text"> {{ product.name |truncatechars:40}} </p>
                    <div
                            class="d-flex justify-content-between align-items-center">
                        <div class="btn-group">
                            <a class="btn btn-dark" href="{%url 'catalog:product_detail' product.pk%}">Перейти</a>
                            {% if user.is_authenticated %}
                            {% if product.owner == user or perms.catalog.can_unpublish_product %}
                            <a class="btn btn-dark" href="{%url 'catalog:product_update' product.pk%}">Редактировать</a>
                            <a class="btn btn-dark" href="{%url 'catalog:product_delete' product.pk%}">удалить</a>
                            {% endif %}
                            {% endif %}
                        </div>
                        <small class="text-body-secondary">{{ product.updated_at|date:"d M Y" }}</small>
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

catalog/templates/catalog/sign.html
{% extends 'catalog/base.html' %}
{% block content %}


{% endblock %}